### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by joaquinez** [peterkuma/ccplot#4]
Hey @peterkuma! I found what seems to be a bug. I am running ccplot on a Mac and so far it seems the install worked, as I shown by command ccplot -V.

So I tried this command: `ccplot -x 0..100 -y 0..100 -c cloudsat-reflectivity.cmap -o cloudsat-reflec.pdf cloudsat-reflec /Users/joaquinx/Documents/Cloudsat/data/029/2016029193244_51898_CS_2B-GEOPROF_GRANULE_P1_R05_E06_F00.hdf`

And got back two errors, one which I think it's because I need to learn more :)
`ccplot: Figure size exceeds 32767 pixels, please specify a smaller region`

The other one might actually be something to improve:
`/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ccplot:1178: MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead. llaxes.axesPatch.set_alpha(0.0)`

Hoping to get ccplot working, thanks so much! fantastic work!

**Comment by peterkuma** [comment]
The command fails because the vertical extent is very small (0 to 100 m). The aspect ratio (data extent of the x axis relative to the y axis) is kept fixed, and it results in a very long plot, which matplotlib is unable to plot. You could for example to select a larger y range with `-y 0..10000` (0 to 10000 m).

The warning has been fixed.

Thank you for this report and sorry for responding very late.
